"""add must_change_password to admin_user

Revision ID: 0e65ba81fcf9
Revises: 0e8b7d6509e5
Create Date: 2026-04-26 15:25:35.307027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e65ba81fcf9'
down_revision: Union[str, None] = '0e8b7d6509e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing admin rows (if any) get must_change_password=True, forcing them
    # to set a new password on next login. Future inserts keep that default
    # via the model-level default.
    op.add_column(
        'admin_user',
        sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'must_change_password')
    # ### end Alembic commands ###
