"""initial schema

Revision ID: 0e8b7d6509e5
Revises: 
Create Date: 2026-04-26 14:26:59.588787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e8b7d6509e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('crew_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_crew',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('crew_member_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_sid', sa.String(length=64), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'crew_member_id'),
    sa.UniqueConstraint('event_id', 'crew_member_id', name='uq_event_crew')
    )
    op.create_table('event_equipment',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_tag_id'], ['equipment_tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'equipment_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_equipment')
    op.drop_table('event_crew')
    op.drop_table('event')
    op.drop_table('equipment_tag')
    op.drop_table('crew_member')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
